// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindMapCodeConflict(arg1, arg2, arg3) {
  return window['go']['downloader']['Downloader']['FindMapCodeConflict'](arg1, arg2, arg3);
}

export function ImportAsset(arg1, arg2, arg3) {
  return window['go']['downloader']['Downloader']['ImportAsset'](arg1, arg2, arg3);
}

export function InstallAsset(arg1) {
  return window['go']['downloader']['Downloader']['InstallAsset'](arg1);
}

export function UninstallAsset(arg1, arg2) {
  return window['go']['downloader']['Downloader']['UninstallAsset'](arg1, arg2);
}
