// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function FindMapCodeConflict(arg1:string,arg2:string,arg3:boolean):Promise<types.MapCodeConflict|boolean>;

export function ImportAsset(arg1:types.AssetType,arg2:string,arg3:boolean):Promise<types.AssetInstallResponse>;

export function InstallAsset(arg1:types.InstallAssetRequest):Promise<types.AssetInstallResponse>;

export function UninstallAsset(arg1:types.AssetType,arg2:string):Promise<types.AssetUninstallResponse>;
