// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function InstallAsset(arg1:types.AssetType,arg2:string,arg3:string):Promise<types.AssetInstallResponse>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UninstallAsset(arg1:types.AssetType,arg2:string):Promise<types.AssetUninstallResponse>;
