// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function InstallMap(arg1:string,arg2:string):Promise<types.MapExtractResponse>;

export function InstallMod(arg1:string,arg2:string):Promise<types.GenericResponse>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UninstallMap(arg1:string):Promise<types.GenericResponse>;

export function UninstallMod(arg1:string):Promise<types.GenericResponse>;
