// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearConfig() {
  return window['go']['config']['Config']['ClearConfig']();
}

export function ClearGithubToken() {
  return window['go']['config']['Config']['ClearGithubToken']();
}

export function CompleteSetup() {
  return window['go']['config']['Config']['CompleteSetup']();
}

export function GetConfig() {
  return window['go']['config']['Config']['GetConfig']();
}

export function GetGithubToken() {
  return window['go']['config']['Config']['GetGithubToken']();
}

export function IsGithubTokenValid() {
  return window['go']['config']['Config']['IsGithubTokenValid']();
}

export function OpenExecutableDialog(arg1) {
  return window['go']['config']['Config']['OpenExecutableDialog'](arg1);
}

export function OpenMetroMakerDataFolderDialog(arg1) {
  return window['go']['config']['Config']['OpenMetroMakerDataFolderDialog'](arg1);
}

export function ResolveConfig() {
  return window['go']['config']['Config']['ResolveConfig']();
}

export function SaveConfig() {
  return window['go']['config']['Config']['SaveConfig']();
}

export function SetConfig(arg1) {
  return window['go']['config']['Config']['SetConfig'](arg1);
}

export function SetContext(arg1) {
  return window['go']['config']['Config']['SetContext'](arg1);
}

export function TryAutoDetectPath(arg1, arg2, arg3, arg4) {
  return window['go']['config']['Config']['TryAutoDetectPath'](arg1, arg2, arg3, arg4);
}

export function UpdateCheckForUpdatesOnLaunch(arg1) {
  return window['go']['config']['Config']['UpdateCheckForUpdatesOnLaunch'](arg1);
}

export function UpdateConfig(arg1, arg2) {
  return window['go']['config']['Config']['UpdateConfig'](arg1, arg2);
}

export function UpdateExecutable(arg1) {
  return window['go']['config']['Config']['UpdateExecutable'](arg1);
}

export function UpdateGithubToken(arg1) {
  return window['go']['config']['Config']['UpdateGithubToken'](arg1);
}

export function UpdateMetroMakerDataFolder(arg1) {
  return window['go']['config']['Config']['UpdateMetroMakerDataFolder'](arg1);
}
