// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function ClearConfig():Promise<types.ResolveConfigResponse>;

export function ClearGithubToken():Promise<types.ResolveConfigResponse>;

export function CompleteSetup():Promise<types.ResolveConfigResponse>;

export function GetConfig():Promise<types.ResolveConfigResponse>;

export function GetGithubToken():Promise<string>;

export function IsGithubTokenValid():Promise<types.GithubTokenValidResponse>;

export function OpenExecutableDialog(arg1:types.SetConfigPathOptions):Promise<types.SetConfigPathResponse>;

export function OpenMetroMakerDataFolderDialog(arg1:types.SetConfigPathOptions):Promise<types.SetConfigPathResponse>;

export function ResolveConfig():Promise<types.ResolveConfigResult>;

export function SaveConfig():Promise<types.ResolveConfigResponse>;

export function SetConfig(arg1:types.AppConfig):Promise<types.AppConfig>;

export function SetContext(arg1:context.Context):Promise<void>;

export function TryAutoDetectPath(arg1:Array<string>,arg2:boolean,arg3:any,arg4:any):Promise<types.SetConfigPathResult|boolean>;

export function UpdateCheckForUpdatesOnLaunch(arg1:boolean):Promise<types.ResolveConfigResponse>;

export function UpdateConfig(arg1:any,arg2:boolean):Promise<types.ResolveConfigResult>;

export function UpdateExecutable(arg1:string):Promise<types.ResolveConfigResult>;

export function UpdateGithubToken(arg1:string):Promise<types.ResolveConfigResponse>;

export function UpdateMetroMakerDataFolder(arg1:string):Promise<types.ResolveConfigResult>;
