// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfileArchive(arg1) {
  return window['go']['profiles']['UserProfiles']['CreateProfileArchive'](arg1);
}

export function GetActiveProfile() {
  return window['go']['profiles']['UserProfiles']['GetActiveProfile']();
}

export function ImportAsset(arg1) {
  return window['go']['profiles']['UserProfiles']['ImportAsset'](arg1);
}

export function LoadProfiles() {
  return window['go']['profiles']['UserProfiles']['LoadProfiles']();
}

export function QuarantineUserProfiles() {
  return window['go']['profiles']['UserProfiles']['QuarantineUserProfiles']();
}

export function ResetUserProfiles() {
  return window['go']['profiles']['UserProfiles']['ResetUserProfiles']();
}

export function RestoreProfileArchive(arg1) {
  return window['go']['profiles']['UserProfiles']['RestoreProfileArchive'](arg1);
}

export function SyncSubscriptions(arg1, arg2) {
  return window['go']['profiles']['UserProfiles']['SyncSubscriptions'](arg1, arg2);
}

export function UpdateSubscriptions(arg1) {
  return window['go']['profiles']['UserProfiles']['UpdateSubscriptions'](arg1);
}

export function UpdateSubscriptionsToLatest(arg1) {
  return window['go']['profiles']['UserProfiles']['UpdateSubscriptionsToLatest'](arg1);
}

export function UpdateSystemPreferences(arg1) {
  return window['go']['profiles']['UserProfiles']['UpdateSystemPreferences'](arg1);
}

export function UpdateUIPreferences(arg1) {
  return window['go']['profiles']['UserProfiles']['UpdateUIPreferences'](arg1);
}
