// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddInstalledMap(arg1, arg2, arg3, arg4) {
  return window['go']['registry']['Registry']['AddInstalledMap'](arg1, arg2, arg3, arg4);
}

export function AddInstalledMod(arg1, arg2, arg3) {
  return window['go']['registry']['Registry']['AddInstalledMod'](arg1, arg2, arg3);
}

export function BootstrapInstalledStateFromProfile(arg1) {
  return window['go']['registry']['Registry']['BootstrapInstalledStateFromProfile'](arg1);
}

export function GetAssetDownloadCounts(arg1, arg2) {
  return window['go']['registry']['Registry']['GetAssetDownloadCounts'](arg1, arg2);
}

export function GetDownloadCountsByAssetType(arg1) {
  return window['go']['registry']['Registry']['GetDownloadCountsByAssetType'](arg1);
}

export function GetGalleryImage(arg1, arg2, arg3) {
  return window['go']['registry']['Registry']['GetGalleryImage'](arg1, arg2, arg3);
}

export function GetGalleryImageResponse(arg1, arg2, arg3) {
  return window['go']['registry']['Registry']['GetGalleryImageResponse'](arg1, arg2, arg3);
}

export function GetInstalledMapCodes() {
  return window['go']['registry']['Registry']['GetInstalledMapCodes']();
}

export function GetInstalledMaps() {
  return window['go']['registry']['Registry']['GetInstalledMaps']();
}

export function GetInstalledMapsResponse() {
  return window['go']['registry']['Registry']['GetInstalledMapsResponse']();
}

export function GetInstalledMods() {
  return window['go']['registry']['Registry']['GetInstalledMods']();
}

export function GetInstalledModsResponse() {
  return window['go']['registry']['Registry']['GetInstalledModsResponse']();
}

export function GetIntegrityReport(arg1) {
  return window['go']['registry']['Registry']['GetIntegrityReport'](arg1);
}

export function GetIntegrityReportResponse(arg1) {
  return window['go']['registry']['Registry']['GetIntegrityReportResponse'](arg1);
}

export function GetMap(arg1) {
  return window['go']['registry']['Registry']['GetMap'](arg1);
}

export function GetMaps() {
  return window['go']['registry']['Registry']['GetMaps']();
}

export function GetMapsResponse() {
  return window['go']['registry']['Registry']['GetMapsResponse']();
}

export function GetMod(arg1) {
  return window['go']['registry']['Registry']['GetMod'](arg1);
}

export function GetMods() {
  return window['go']['registry']['Registry']['GetMods']();
}

export function GetModsResponse() {
  return window['go']['registry']['Registry']['GetModsResponse']();
}

export function GetVersions(arg1, arg2) {
  return window['go']['registry']['Registry']['GetVersions'](arg1, arg2);
}

export function GetVersionsResponse(arg1, arg2) {
  return window['go']['registry']['Registry']['GetVersionsResponse'](arg1, arg2);
}

export function Initialize() {
  return window['go']['registry']['Registry']['Initialize']();
}

export function Refresh() {
  return window['go']['registry']['Registry']['Refresh']();
}

export function RefreshResponse() {
  return window['go']['registry']['Registry']['RefreshResponse']();
}

export function RemoveInstalledMap(arg1) {
  return window['go']['registry']['Registry']['RemoveInstalledMap'](arg1);
}

export function RemoveInstalledMod(arg1) {
  return window['go']['registry']['Registry']['RemoveInstalledMod'](arg1);
}

export function SetInstalledMapsFromPath(arg1) {
  return window['go']['registry']['Registry']['SetInstalledMapsFromPath'](arg1);
}

export function SetInstalledModsFromPath(arg1) {
  return window['go']['registry']['Registry']['SetInstalledModsFromPath'](arg1);
}

export function WriteInstalledToDisk() {
  return window['go']['registry']['Registry']['WriteInstalledToDisk']();
}
