// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function ClearConfig():Promise<types.AppConfig>;

export function ResolveConfig():Promise<types.ResolveConfigResult>;

export function SetConfig(arg1:types.AppConfig):Promise<types.AppConfig>;

export function UpdateExecutable(arg1:string):Promise<types.AppConfig>;

export function UpdateMetroMakerDataFolder(arg1:string):Promise<types.AppConfig>;
