// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallMap(arg1, arg2) {
  return window['go']['main']['Downloader']['InstallMap'](arg1, arg2);
}

export function InstallMod(arg1, arg2) {
  return window['go']['main']['Downloader']['InstallMod'](arg1, arg2);
}
