// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetGalleryImage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetInstalledMapCodes():Promise<Array<string>>;

export function GetInstalledMaps():Promise<Array<string>>;

export function GetInstalledMods():Promise<Array<string>>;

export function GetMaps():Promise<Array<types.MapManifest>>;

export function GetMods():Promise<Array<types.ModManifest>>;

export function GetVersions(arg1:string,arg2:string):Promise<Array<types.VersionInfo>>;

export function Initialize():Promise<void>;

export function Refresh():Promise<void>;
