// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function ClearProfile(arg1:string):Promise<types.UserProfile>;

export function GetActiveProfile():Promise<types.UserProfile>;

export function GetProfile(arg1:string):Promise<types.UserProfile>;

export function LoadProfiles():Promise<types.UserProfilesState>;

export function SetActiveProfile(arg1:string):Promise<types.UserProfilesState>;

export function SetProfile(arg1:string,arg2:types.UserProfile):Promise<types.UserProfile>;
