// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearProfile(arg1) {
  return window['go']['main']['UserProfiles']['ClearProfile'](arg1);
}

export function GetActiveProfile() {
  return window['go']['main']['UserProfiles']['GetActiveProfile']();
}

export function GetProfile(arg1) {
  return window['go']['main']['UserProfiles']['GetProfile'](arg1);
}

export function LoadProfiles() {
  return window['go']['main']['UserProfiles']['LoadProfiles']();
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['UserProfiles']['SetActiveProfile'](arg1);
}

export function SetProfile(arg1, arg2) {
  return window['go']['main']['UserProfiles']['SetProfile'](arg1, arg2);
}
